export const SET_GAME_SPEED = "SET_GAME_SPEED"
export const SET_SEQUENCE = "SET_SEQUENCE"
export const SET_SEQUENCE_TO_GUESS = "SET_SEQUENCE_TO_GUESS"
export const SET_ROUND_NUMBER = "SET_ROUND_NUMBER"